### ISSUE TITLE
actionbar notify not work

### ISSUE THREAD

**Issue by mat41997** [FabioZumbi12/RedProtect#152]
config
```
notify:
  region-enter: true
  region-exit: false
  region-enter-mode: ACTIONBAR
  welcome-mode: ACTIONBAR
```
ss
![6209b417b45eb4238e9cd663c0f13e8d414ecc5a](https://cloud.githubusercontent.com/assets/5884000/23699983/96ca2a3c-03f1-11e7-9d80-21b7621da19c.png)
