### ISSUE TITLE
PvP turns off on region enter

### ISSUE THREAD

**Issue by CloudeLecaw** [FabioZumbi12/RedProtect#263]
When a Player enters a Region and has Pvp tunred on his PvP get turned off
When he leaved the Region it gets turned on aggain

Spigot: 1.12.2
redprotect: RedProtect-7.4.0-Build88
Hook with: PvPManager (Paid)

Pvp Flag is: enabled

**Comment by CloudeLecaw** [comment]
Hello Fabio i have still this Problem

Here is how it happens on my Server:

```
Testarea:
  name: Testarea
  lastvisit: 02/05/2018
  admins: []
  members: []
  leaders:
  - f24df990-9c6b-4f32-938a-4c91a26d31f4
  priority: 0
  welcome: ''
  world: Demantra
  maxX: 591
  maxZ: 148
  minX: 582
  minZ: 138
  maxY: 256
  minY: 0
  value: 0
  flags:
    leaves-decay: false
    allow-effects: true
    door: false
    can-death: true
    invincible: false
    sign: true
    allow-spawner: false
    can-pet: true
    keep-inventory: false
    fire: false
    enter: true
    flow: true
    forcefly: false
    up-skills: true
    allow-home: true
    chest: false
    smart-door: true
    keep-levels: false
    cropsfarm: true
    use-potions: true
    lever: false
    pvp: false
    allow-elytra: false
    passives: false
    portal-enter: true
    exit: true
    minecart: false
    can-pickup: true
    allow-potions: true
    can-grow: true
    dynmap: ''
    spawn-wither: false
    can-projectiles: true
    portal-exit: true
    teleport: false
    minefarm: true
    allow-create-portal: true
    mob-loot: false
    button: false
    pvparena: false
    player-damage: true
    iceform-player: true
    can-drop: true
    allow-mod: true
    iceform-world: true
    forcepvp: false
    can-back: true
    spawn-animals: true
    ender-chest: true
    treefarm: true
    allow-fly: false
    build: false
    flow-damage: false
    spawn-monsters: true
    can-hunger: true
  candelete: true
  tppoint: ''
```

i turn on PvP in Wilderness - PVP is on
i move one step - pvp got turned off
i went into the Region - pvpv is tunred on

This just effects Players not Admins ( i think because of a Bypass)
