### ISSUE TITLE
Player can destory blocks

### ISSUE THREAD

**Issue by CloudeLecaw** [FabioZumbi12/RedProtect#287]
stranger Players cant place but destory blocks in a Region
pls fix it 🥉 

Some blocks like sign chest, signs etc are probected but many full blocks like dirt, grass, Stone etc can be broken, may it has to do with the ID channge?

Used Version: RedProtect_7.4.1-Build111.jar
Spigot: 1.13-Pre7

Edit: Sometimes some blocks seem to be protected, often not... i see no logic in what is protected what not..

here a templeate from my TestRegion:
```
Testregion:
  name: Testregion
  lastvisit: 20/07/2018
  admins: []
  members: []
  leaders:
  - '#server#'
  priority: 0
  welcome: ''
  world: PreWelt
  maxX: 2000
  maxZ: 2000
  minX: 1950
  minZ: 1950
  maxY: 256
  minY: 0
  value: 0
  flags:
    leaves-decay: false
    allow-effects: true
    door: false
    can-death: true
    invincible: false
    sign: true
    allow-spawner: false
    can-pet: true
    keep-inventory: false
    fire: true
    enter: true
    flow: true
    forcefly: false
    up-skills: true
    allow-home: false
    chest: false
    smart-door: true
    keep-levels: false
    cropsfarm: true
    use-potions: true
    lever: false
    pvp: false
    allow-elytra: false
    passives: false
    portal-enter: true
    exit: true
    minecart: false
    can-pickup: true
    allow-potions: true
    can-grow: true
    dynmap: ''
    spawn-wither: false
    can-projectiles: true
    portal-exit: true
    teleport: false
    minefarm: true
    allow-create-portal: true
    mob-loot: false
    button: false
    pvparena: false
    player-damage: true
    iceform-player: true
    can-drop: true
    allow-mod: true
    iceform-world: true
    can-back: true
    spawn-animals: true
    ender-chest: true
    treefarm: true
    allow-fly: false
    build: false
    flow-damage: false
    spawn-monsters: true
    can-hunger: true
  candelete: true
  tppoint: ''
```

Edit: look first like all Kinds of stone and dirt are effected while other blocks are protected)
