### ISSUE TITLE
No Lava Flow in 7.4.1

### ISSUE THREAD

**Issue by AokuYuki** [FabioZumbi12/RedProtect#289]
_Put if is the **Spigot** or **Sponge** version._  
Platform: spongeforge-1.12.2-2705-7.1.0-BETA-3328.jar

_Inform you RedProtect jar name like **RedProtect-Spigot-7.0.3.jar**._  
Jar version:  RedProtect-7.4.1-b111-Universal.jar

_Your server Minecraft version_  
Minecraft version:  1.12.2

_Issue or Suggestion?_  
What you want?:  
In RedProtect-7.4.1-b111-Universal.jar lava wont flow, even thought all configs of lava flow are set to true. The Server is new, so no claims are made yet.
If i replace it with RedProtect-7.3.0-b68-Universal.jar , lava flows just fine.
How can i make lava flow in RedProtect-7.4.1-b111-Universal.jar?

**Comment by CloudeLecaw** [comment]
![image](https://user-images.githubusercontent.com/12080017/43260710-8ab64b64-90da-11e8-935f-a6b7e1f71e2d.png)

global:
```
Demantra_old:
  build: true
  liquid-flow: true
  allow-changes-of:
    water-flow: true
    lava-flow: true
    leaves-decay: true
    flow-damage: true
  if-build-false:
    break-blocks: []
    place-blocks: []
  pvp: false
  iceform-by:
    player: false
    world: true
  interact: true
  if-interact-false:
    allow-blocks: []
    allow-entities: []
  use-minecart: true
  entity-block-damage: true
  explosion-entity-damage: true
  fire-block-damage: false
  fire-spread: false
  player-hurt-monsters: true
  player-hurt-passives: true
  spawn-monsters: true
  spawn-passives: true
  remove-entities-not-allowed-to-spawn: false
  elytra:
    allow: true
    boost: 0.5
  deny-item-usage:
    allow-on-claimed-rps: true
    allow-on-wilderness: true
    items: []
  player-velocity:
    walk-speed: -1.0
    fly-speed: -1.0
  on-enter-cmds: []
  on-exit-cmds: []
  spawn-wither: true
  invincible: false
  player-candrop: true
  player-canpickup: true
  rain:
    trys-before-rain: 3
    duration: 60
  allow-crops-trample: false
  command-ranges:
    home:
      min-range: 0.0
      max-range: 256.0
      message: '&cDu kannst kein /home in diese Höhe setzen.'
```

Region:
```
Spawn2:
  name: Spawn2
  lastvisit: 12/06/2018
  admins: []
  members: []
  leaders:
  - '#server#'
  priority: 0
  welcome: 'hide '
  world: Demantra_old
  maxX: 575
  maxZ: 150
  minX: 425
  minZ: 25
  maxY: 256
  minY: 0
  value: 0
  flags:
    leaves-decay: false
    allow-effects: true
    door: true
    can-death: true
    invincible: false
    sign: true
    allow-spawner: false
    can-pet: true
    keep-inventory: false
    fire: false
    enter: true
    flow: false
    forcefly: false
    up-skills: true
    allow-home: false
    chest: true
    smart-door: true
    keep-levels: false
    cropsfarm: true
    use-potions: true
    lever: true
    pvp: false
    allow-elytra: false
    passives: false
    portal-enter: true
    exit: true
    minecart: false
    can-pickup: true
    allow-potions: true
    can-grow: true
    dynmap: ''
    spawn-wither: false
    can-projectiles: true
    portal-exit: true
    teleport: true
    minefarm: false
    allow-create-portal: true
    mob-loot: false
    button: true
    pvparena: false
    player-damage: true
    iceform-player: false
    can-drop: true
    allow-mod: true
    iceform-world: false
    can-back: true
    spawn-animals: false
    ender-chest: true
    treefarm: false
    allow-fly: false
    build: false
    flow-damage: false
    spawn-monsters: false
    can-hunger: true
  candelete: true
  tppoint: ''
```

the Regionflag is  **flow**
the globalflag is: **lava-flow**
