### ISSUE TITLE
farmland get destroyed

### ISSUE THREAD

**Issue by CloudeLecaw** [FabioZumbi12/RedProtect#697]
When you have the flag cropsfarm aktive all crops can be used and player can work as farmer.
but if there is a farmlandblock then player can destory it
Thy should work on the farmland not destory it and also these block can not be placed without right flag

![image](https://user-images.githubusercontent.com/12080017/93405233-bee4d880-f88c-11ea-90f6-dfa6bbc3230a.png)
![image](https://user-images.githubusercontent.com/12080017/93406256-7da1f800-f88f-11ea-8f20-792aa01f6b40.png)

Paper Version 1.16.3 - Build 195
RedProtect-7.7.2-b377-Universal.jar

**Comment by FabioZumbi12** [comment]
This still on latest dev builds? I think i have fixed in a later version.

**Comment by CloudeLecaw** [comment]
yes the farmland still can be broken

Here is the region file from us:
```
FarmResTestWelt:
  name: FarmResTestWelt
  lastvisit: 23/11/2020
  admins: []
  members: []
  leaders:
  - '#server#@#server#'
  priority: -1
  welcome: 'hide '
  world: testwelt
  maxX: -264
  maxZ: 299
  minX: -292
  minZ: 253
  maxY: 63
  minY: 62
  value: 0
  flags:
    can-grow: true
    leaves-decay: false
    allow-effects: false
    door: false
    can-projectiles: false
    teleport: false
    allow-spawner: false
    mob-loot: false
    button: false
    allow-place: BEETROOT,BEETROOT_SEEDS,BONE_MEAL,CARROT,NETHER_WART,POTATO,SWEET_BERRIES,WHEAT,WHEAT_SEEDS
    allow-magiccarpet: false
    fire: false
    flow: false
    iceform-player: false
    allow-home: false
    chest: false
    allow-mod: false
    iceform-world: false
    smart-door: false
    fishing: false
    use-potions: false
    cropsfarm: true
    lever: false
    pvp: false
    spawn-animals: false
    passives: false
    press-plate: false
    minecart: false
    ender-chest: false
    allow-fly: false
    build: false
    allow-break: BEETROOT,BEETROOT_SEEDS,BONE_MEAL,CARROT,NETHER_WART,POTATO,SWEET_BERRIES,WHEAT,WHEAT_SEEDS
    gravity: false
    flow-damage: false
    spawn-monsters: false
    floristics: true
    block-transform: false
    redstone: false
    killer-projectiles: false
  candelete: true
  canpurge: true
  tppoint: ''
```
cropsfarm true is needed to be able to seed wheet and others and farm them. but they shurt not be able to destroy the farmland under it
