### ISSUE TITLE
many flags dont work when driving into a zone (1.16.5)

### ISSUE THREAD

**Issue by CloudeLecaw** [FabioZumbi12/RedProtect#735]
We have some nice flags like the execute servercommands or gamemode flag that can interact when enterings or leaving a region.

We noticed a lot of these flags work wonderfull if you walk, run or tp into that region.
But if you where on a rail and enter the region with a minecart then these flags cant be executed until you leave the minecart.
Seems like this does not count as "entering" and "leaving"...

We wrote thisproblem allready to an other plugin dev from a portal plugin with same issue. He fixed it allready what means - the problem can be fixed here too :-)

I think this problem may takes some eyes on it. because it happen often that you leave or enter a region in a minecart.

`Versions:  Redprotect 7.2.2 Build 385
PaperMC:  1.16.5 - Build 445`

![Snag_2fbe5dc](https://user-images.githubusercontent.com/12080017/105615590-24644b00-5dd2-11eb-9fd2-0c2fef8c4e5a.png)

Region Example:
```
Geisterbahn4:
  name: Geisterbahn4
  lastvisit: 27/01/2021
  admins: []
  members: []
  leaders:
  - '#server#@#server#'
  priority: 4
  welcome: 'hide '
  world: world
  maxX: -407
  maxZ: 285
  minX: -431
  minZ: 277
  maxY: 29
  minY: 19
  value: 0
  flags:
    can-grow: true
    leaves-decay: true
    allow-effects: true
    door: false
    dynmap: false
    can-projectiles: false
    teleport: false
    allow-spawner: false
    mob-loot: false
    server-enter-command: cmi playercollision {player} false -s,cmi gm adventure {player} -s
    button: false
    player-damage: false
    allow-magiccarpet: true
    fire: false
    server-exit-command: cmi playercollision {player} true -s,cmi gm survival {player} -s
    flow: true
    iceform-player: true
    allow-home: false
    chest: false
    allow-mod: true
    iceform-world: true
    smart-door: true
    fishing: true
    use-potions: true
    lever: false
    pvp: false
    spawn-animals: false
    passives: false
    press-plate: false
    minecart: false
    ender-chest: true
    allow-fly: false
    build: false
    gravity: true
    flow-damage: false
    spawn-monsters: SPIDER
    floristics: false
    block-transform: true
    redstone: false
    killer-projectiles: false
  candelete: true
  canpurge: true
```
