### ISSUE TITLE
Enter Region in chat in Redprotect 8.0.0?....[BUG] 

### ISSUE THREAD

**Issue by CloudeLecaw** [FabioZumbi12/RedProtect#820]
noraly we had this setting:

```
# Show messages on enter, exit and welcome messages.
notify {
    region-enter=true
    # Available: "BOSSBAR", "OFF" or "CHAT"
    region-enter-mode=BOSSBAR
    # Notify on exit region? (in most cases will be wilderness)
    region-exit=true
    # Available: "BOSSBAR", "OFF" or "CHAT"
    welcome-mode=BOSSBAR
    welcome-region-name=false
}
```

but when we went to spawn the meassge is not shown in bossbar it shown in chat..

https://streamable.com/33bet2

![Snag_99e7c3d](https://user-images.githubusercontent.com/12080017/174473284-b107450b-99a1-43ca-b2a8-7a94811a0551.png)

```
Blueland:
  name: Blueland
  lastvisit: 19/06/2022
  admins: []
  members: []
  leaders:
  - '#server#@#server#'
  priority: 0
  welcome: 'Spawn '
  world: world
  maxX: 605
  maxZ: 643
  minX: -230
  minZ: -153
  maxY: 320
  minY: -64
  value: 0
  flags:
    can-grow: false
    leaves-decay: false
    allow-effects: true
    door: true
    dynmap: true
    can-projectiles: true
    portal-exit: false
    teleport: false
    allow-spawner: false
    mob-loot: false
    button: true
    pvparena: false
    allow-place: BLUE_SHULKER_BOX,TNT
    player-damage: true
    allow-magiccarpet: false
    keep-inventory: false
    fire: false
    flow: true
    iceform-player: true
    allow-home: false
    chest: true
    can-drop: true
    allow-mod: true
    iceform-world: true
    smart-door: false
    fishing: true
    use-potions: true
    cropsfarm: false
    lever: true
    pvp: false
    spawn-animals: true
    passives: false
    press-plate: true
    minecart: true
    ender-chest: true
    allow-fly: true
    build: false
    allow-break: BLUE_SHULKER_BOX,TNT
    gravity: true
    flow-damage: false
    spawn-monsters: 'false'
    floristics: false
    block-transform: false
    redstone: false
    killer-projectiles: false
  candelete: true
  canpurge: true
  tppoint: ''
```
